[package]
name = "wootheex_nif"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "wootheex_nif"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.21.0"
lazy_static = "1.0"
woothee = { git = "https://github.com/arikai/woothee-rust.git", branch = "feat/kitkat-webview" }
